language: cpp
dist: xenial
os:
  - linux
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y qtbase5-dev libqt5webkit5-dev libqt5svg5-dev qttools5-dev-tools
script:
  - ./configure && make
  - (cd src/ui-tests && qmake && make && ./ui-tests)
