language: cpp
dist: trusty
sudo: required
os:
  - linux
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y qtbase5-dev libqt5webkit5-dev libqt5svg5-dev qttools5-dev-tools
script:
  - "./configure && make"
  - "./src/ui-tests/ui-tests"
before_deploy:
  - "tar -zcf notepadqq-${TRAVIS_TAG:-${TRAVIS_COMMIT}}-x86_64.tar.gz -C out release"
deploy:
  provider: releases
  api_key:
    secure: OCEuXR1a2dDHKKQpnOeSoeWZeL0clf0eVUZt5QbrnkyvL3/iUHXjYbdVBEGrbuldffLy9YOC63viqh/r7Ak+7k/suG1BxwGczbvtMBvRyUOOI48YX90Ss+JUcpvJVNLoirDqA1hPMho5Rmydu+DFRlpjADfg3KtZZZA+8Xz8Uek=
  file: "notepadqq-${TRAVIS_TAG:-${TRAVIS_COMMIT}}-x86_64.tar.gz"
  skip_cleanup: true
  on:
    repo: notepadqq/notepadqq
